CarsSaaber/Models/CarsSaaber/CarsSaaberCreateUpdateViewModel.cs
namespace CarsSaaber.Models.CarsSaaber
{
    public class CarsSaaberCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public int Discount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

CarsSaaber/Models/CarsSaaber/CarsSaaberDeleteViewModel.cs
namespace CarsSaaber.Models.CarsSaaber
{
    public class CarsSaaberDeleteViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public int Discount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

CarsSaaber/Models/CarsSaaber/CarsSaaberDetailsViewModel.cs
namespace CarsSaaber.Models.CarsSaaber
{
    public class CarsSaaberDetailsViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public int Discount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

CarsSaaber/Models/CarsSaaber/CarsSaaberIndexViewModel.cs
namespace CarsSaaber.Models.CarsSaaber
{
    public class CarsSaaberIndexViewModel
    {
        public Guid? Id { get; set; }
        public int Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string Color { get; set; }
        public int Discount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

CarsSaaber/Models/ErrorViewModel.cs
namespace CarsSaaber.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarsSaaber/Controllers/CarsSaaberController.cs
using CarsSaaber.Core.Dto;
using CarsSaaber.Core.ServiceInterface;
using CarsSaaber.Data;
using CarsSaaber.Models.CarsSaaber;
using Microsoft.AspNetCore.Mvc;

namespace CarsSaaber.Controllers
{
    public class CarsSaaberController : Controller
    {
        private readonly CarsContext _context;
        private readonly ICarsSaaberServices _carServices;

        public CarsSaaberController
            (
                CarsContext context, 
                ICarsSaaberServices carServices
            )
        {
            _context = context;
            _carServices = carServices;
        }

        public IActionResult Index()
        {
            var result = _context.CarsSaaber
                .OrderBy((key) => key.CreatedAt)
                .Select(x => new CarsSaaberIndexViewModel
                {
                    Id = x.Id,
                    Price = x.Price,
                    Brand = x.Brand,
                    Model = x.Model,
                    Year = x.Year,
                    Color = x.Color,
                    Discount = x.Discount,
                });

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsSaaberDetailsViewModel();

            vm.Id = car.Id;
            vm.Price = car.Price;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.Year = car.Year;
            vm.Color = car.Color;
            vm.Discount = car.Discount;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View(vm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CarsSaaberCreateUpdateViewModel car = new CarsSaaberCreateUpdateViewModel();

            return View("CreateUpdate", car);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarsSaaberCreateUpdateViewModel vm)
        {
            var dto = new CarsDto()
            {
                Id = vm.Id,
                Price = vm.Price,
                Brand = vm.Brand,
                Model = vm.Model,
                Year = vm.Year,
                Color = vm.Color,
                Discount = vm.Discount,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };

            var result = await _carServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsSaaberCreateUpdateViewModel();

            vm.Id = car.Id;
            vm.Price = car.Price;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.Year = car.Year;
            vm.Color = car.Color;
            vm.Discount = car.Discount;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CarsSaaberCreateUpdateViewModel vm)
        {
            var dto = new CarsDto()
            {
                Id = vm.Id,
                Price = vm.Price,
                Brand = vm.Brand,
                Model = vm.Model,
                Year = vm.Year,
                Color = vm.Color,
                Discount = vm.Discount,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = DateTime.Now,
            };

            var result = await _carServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var car = await _carServices.GetAsync(id);

            if (car == null)
            {
                return NotFound();
            }

            var vm = new CarsSaaberDeleteViewModel();

            vm.Id = car.Id;
            vm.Price = car.Price;
            vm.Brand = car.Brand;
            vm.Model = car.Model;
            vm.Year = car.Year;
            vm.Color = car.Color;
            vm.Discount = car.Discount;
            vm.CreatedAt = car.CreatedAt;
            vm.UpdatedAt = car.UpdatedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var carId = await _carServices.Delete(id);

            if (carId == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarsSaaber/Controllers/HomeController.cs
using CarsSaaber.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarsSaaber.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarsSaaber/Views/CarsSaaber/CreateUpdate.cshtml
@model CarsSaaber.Models.CarsSaaber.CarsSaaberCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Brand" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Model" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Year" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Year" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Color" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Color" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Discount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Discount" class="form-control" />
            </div>
        </div>

        <hr />

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="CarsSaaber" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="CarsSaaber" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

CarsSaaber/Views/CarsSaaber/Delete.cshtml
@model CarsSaaber.Models.CarsSaaber.CarsSaaberDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Price)
        </div>

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Brand)
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Model)
        </div>

        <div class="form-group row">
            <label asp-for="Year" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Year)
        </div>

        <div class="form-group row">
            <label asp-for="Color" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Color)
        </div>

        <div class="form-group row">
            <label asp-for="Discount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Discount)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.UpdatedAt)
        </div>
    </dl>
    <hr />
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="index" class="btn btn-primary">Index</a>
    </form>
</div>

CarsSaaber/Views/CarsSaaber/Details.cshtml
@model CarsSaaber.Models.CarsSaaber.CarsSaaberDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Price)
        </div>

        <div class="form-group row">
            <label asp-for="Brand" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Brand)
        </div>

        <div class="form-group row">
            <label asp-for="Model" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Model)
        </div>

        <div class="form-group row">
            <label asp-for="Year" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Year)
        </div>

        <div class="form-group row">
            <label asp-for="Color" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Color)
        </div>

        <div class="form-group row">
            <label asp-for="Discount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.Discount)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => Model.UpdatedAt)
        </div>
    </dl>
    <hr />
    <a asp-action="index" class="btn btn-primary">Index</a>
</div>

CarsSaaber/Views/CarsSaaber/Index.cshtml
@model IEnumerable<CarsSaaber.Models.CarsSaaber.CarsSaaberIndexViewModel>

<div class="h1">
    Cars
</div>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="CarsSaaber" class="btn btn-primary">Create</a>
</div>

<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Price</th>
                <th scope="col">Brand</th>
                <th scope="col">Model</th>
                <th scope="col">Year</th>
                <th scope="col">Color</th>
                <th scope="col">Discount</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var car in Model)
                {
                    <tr>
                        <td>@(rowNumber++)</td>
                        <td>@car.Price</td>
                        <td>@car.Brand</td>
                        <td>@car.Model</td>
                        <td>@car.Year</td>
                        <td>@car.Color</td>
                        <td>@car.Discount</td>
                        <td>
                            <a asp-action="details" asp-controller="CarsSaaber" asp-route-id="@car.Id" class="btn btn-info">Details</a>
                            <a asp-action="update" asp-controller="CarsSaaber" asp-route-id="@car.Id" class="btn btn-outline-primary">Update</a>
                            <a asp-action="delete" asp-controller="CarsSaaber" asp-route-id="@car.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>

</form>

CarsSaaber/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CarsSaaber/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarsSaaber</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarsSaaber.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarsSaaber</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarsSaaber" asp-action="Index">CarsSaaber</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarsSaaber - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>